# Original idea by @ISnackable. Many thanks to him for handling the most hardest parts!
# https://github.com/ISnackable/CercubePlus/blob/main/.github/workflows/Build.yml

name: Build CercubePlus Artifact

on:
  workflow_dispatch:
    inputs:
      cercube_version:
        description: "The version of Cercube"
        default: "5.3.9"
        required: false
        type: string
      decrypted_youtube_url:
        description: "The direct URL to the decrypted YouTube ipa"
        default: ""
        required: true
        type: string
      youtube_version:
        description: "The version of YouTube"
        default: ""
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build CercubePlus
    runs-on: macos-latest

    steps:
      - name: Checkout Main
        uses: actions/checkout@v3
        with:
          path: main
          submodules: recursive

      - name: Install Dependencies
        run: brew install ldid dpkg

      - name: Setup Theos
        uses: actions/checkout@v3
        with:
          repository: theos/theos
          ref: master
          path: theos
          submodules: recursive

      - name: Download iOS 15 SDK
        run: |
          curl -LO https://github.com/chrisharper22/sdks/archive/main.zip
          TMP=$(mktemp -d)
          unzip -qq main.zip -d $TMP
          mv $TMP/sdks-main/*.sdk $THEOS/sdks
          rm -r main.zip $TMP
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Setup Theos Jailed
        uses: actions/checkout@v3
        with:
          repository: kabiroberai/theos-jailed
          ref: master
          path: theos-jailed
          submodules: recursive

      - name: Install Theos Jailed
        run: |
          ./theos-jailed/install
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Download Dylibs
        run: |
          curl "https://raw.githubusercontent.com/Muirey03/RemoteLog/master/RemoteLog.h" --output "$THEOS/include/RemoteLog.h"
          curl "https://apt.alfhaily.me/files/me.alfhaily.cercube_${{ env.CERCUBE_VERSION }}_iphoneos-arm.deb" --output "./main/Tweaks/Cercube/me.alfhaily.cercube_${{ env.CERCUBE_VERSION }}_iphoneos-arm.deb"
          wget "$YOUTUBE_URL" --no-verbose -O ./main/YouTube.ipa
          dpkg-deb -x "./main/Tweaks/Cercube/me.alfhaily.cercube_${{ env.CERCUBE_VERSION }}_iphoneos-arm.deb" ./main/Tweaks/Cercube/
          unzip -q ./main/YouTube.ipa -d ./main/tmp
          rm -rf ./main/tmp/Payload/YouTube.app/PlugIns/*
          cp -R ./main/Extensions/*.appex ./main/tmp/Payload/YouTube.app/PlugIns

        env:
          THEOS: ${{ github.workspace }}/theos
          CERCUBE_VERSION: ${{ github.event.inputs.cercube_version }}
          YOUTUBE_URL: ${{ github.event.inputs.decrypted_youtube_url }}

      - name: Fix Compiling && Build Package
        id: build_package
        run: |
          cd ${{ github.workspace }}/main
          (cd ${{ github.workspace }}/main/Tweaks/YouPiP && sed -i '' "14s#.*#YouPiP_FRAMEWORKS = AVKit AVFoundation UIKit#g" ./Makefile)
          make package FINALPACKAGE=1
          (mv "packages/$(ls -t packages | head -n1)" "packages/CercubePlus_${{ env.YOUTUBE_VERSION  }}_${{ env.CERCUBE_VERSION }}.ipa")
          echo "::set-output name=package::$(ls -t packages | head -n1)"
        env:
          THEOS: ${{ github.workspace }}/theos
          CERCUBE_VERSION: ${{ github.event.inputs.cercube_version }}
          YOUTUBE_VERSION: ${{ github.event.inputs.youtube_version }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        env:
          CERCUBE_VERSION: ${{ github.event.inputs.cercube_version }}
          YOUTUBE_VERSION: ${{ github.event.inputs.youtube_version }}
        with:
          name: CercubePlus_${{ env.YOUTUBE_VERSION  }}_${{ env.CERCUBE_VERSION }}
          path: ${{ github.workspace }}/main/packages/${{ steps.build_package.outputs.package }}
          if-no-files-found: error
